version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flaskapp

permissions:
  - object: /home/ubuntu/flaskapp
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:

  BeforeInstall:
    - location: scripts/installflask.sh
      runas: root
  AfterInstall:
    - location: scripts/startflask.sh
      runas: root
    - location: scripts/restartflask.sh
      runas: root
